spring:
  application:
    name: tilias-web-management
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/tilias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456Qq

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true